using Dapper;

public class UserRepository : IUserRepository
{
    private readonly DbConnectionFactory _factory;

    public UserRepository(DbConnectionFactory factory)
    {
        _factory = factory;
    }

    public async Task<Guid> CreateAsync(User user)
    {
        using var connection = _factory.CreateConnection();
        // id and uid are auto-generated by DB (gen_random_uuid())
        var sql = @"INSERT INTO users (name, email, password_hash, role, is_email_verified, otp_code, otp_expires_at)
                    VALUES (@Name, @Email, @PasswordHash, @Role, @IsEmailVerified, @OtpCode, @OtpExpiresAt)
                    RETURNING id";

        return await connection.QuerySingleAsync<Guid>(sql, user);
    }

    public async Task<User?> GetByEmailAsync(string email)
    {
        using var connection = _factory.CreateConnection();
        var sql = "SELECT * FROM users WHERE LOWER(email) = LOWER(@Email)";
        return await connection.QueryFirstOrDefaultAsync<User>(sql, new { Email = email });
    }

    public async Task<User?> GetByIdAsync(Guid id)
    {
        using var connection = _factory.CreateConnection();
        var sql = "SELECT * FROM users WHERE id = @Id";
        return await connection.QueryFirstOrDefaultAsync<User>(sql, new { Id = id });
    }

    public async Task UpdateAsync(User user)
    {
        using var connection = _factory.CreateConnection();
        var sql = @"UPDATE users 
                    SET name = @Name,
                        email = @Email,
                        password_hash = @PasswordHash,
                        role = @Role,
                        is_email_verified = @IsEmailVerified,
                        otp_code = @OtpCode,
                        otp_expires_at = @OtpExpiresAt,
                        reset_otp_code = @ResetOtpCode,
                        reset_otp_expires_at = @ResetOtpExpiresAt,
                        updated_at = NOW()
                    WHERE id = @Id";
        await connection.ExecuteAsync(sql, user);
    }
}