using Dapper;

public class UserRepository : IUserRepository
{
    private readonly DbConnectionFactory _factory;

    public UserRepository(DbConnectionFactory factory)
    {
        _factory = factory;
    }

    public async Task<Guid> CreateAsync(User user)
    {
        using var connection = _factory.CreateConnection();
        // id and uid are auto-generated by DB (gen_random_uuid())
        var sql = @"INSERT INTO users (name, email, password_hash, role)
                    VALUES (@Name, @Email, @PasswordHash, @Role)
                    RETURNING id";

        return await connection.QuerySingleAsync<Guid>(sql, user);
    }

    public async Task<User?> GetByEmailAsync(string email)
    {
        using var connection = _factory.CreateConnection();
        var sql = "SELECT * FROM users WHERE email = @Email";
        return await connection.QueryFirstOrDefaultAsync<User>(sql, new { Email = email });
    }

    public async Task<User?> GetByIdAsync(Guid id)
    {
        using var connection = _factory.CreateConnection();
        var sql = "SELECT * FROM users WHERE id = @Id";
        return await connection.QueryFirstOrDefaultAsync<User>(sql, new { Id = id });
    }
}